version: '3'


services:

  postgres:
    image: postgres
    container_name: postgres_db
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: questions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  web:
    build: .
    container_name: quiz_app
    command: sh -c 'python3 manage.py collectstatic --no-input & python3 manage.py makemigrations --no-input &&
               python3 manage.py migrate --no-input && gunicorn bewise.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - static:/static
      - media:/media
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media: